publishedAt: "2026-09-11"

image: "/images/Jasmijn_en_Jasmijn_voor_klas_HAI.jpg"
imageClasses: "object-right"
ogImage: "/images/Jasmijn_en_Jasmijn_voor_klas_HAI2.jpg"

externalLinks:
  - label: "HAI"
    href: "https://haighana.edu.gh"

  - label: "GIZ"
    href: "https://www.giz.de/de"

hashtags:
  - Pharma4Ghana
  - Ghana
  - PharmacyEducation