publishedAt: "2026-09-04"

image: "/images/posts/graduated_students_2026.jpeg"
ogImage: "/images/posts/graduated_students_2026.jpeg"

externalLinks:
  - label: "Brocacef"
    href: "https://www.linkedin.com/company/brocacef/"

  - label: "contact@pharma4ghana.com"
    href: "mailto:contact@pharma4ghana.com"

hashtags:
  - Pharma4Ghana
  - GlobalHealth
  - Pharmacy
  - HealthcareEducation
  - Ghana
  - Education
  - Healthcare
  - Brocacef